### ISSUE TITLE
TinyMce bug with multiple text areas

### ISSUE THREAD

**Issue by ishareab** [josegonzalez/cakephp-wysiwyg#11]
It's not possible to use the TinyMce on multiple textareas. The last one never loads. This is independent on how many there are. I've tried with 4 and 2. Last one is always a simple textarea.

**Comment by nortechtitanium** [comment]
I modified "app/Plugin/Wysiwyg/view/Helper/TinymceHelper.php"
line 53 to 55.
This my modified section:
/* 
add new variable ($ownLoadVar)  in exploding the "Modelname.fieldname" 
and modify $script variable.
*/
$ownLoadVar= explode(".", $fieldName); 
$script = "var docLoaded".$ownLoadVar[1]." = setInterval(function () {if(document.readyState === 'complete') {clearInterval(docLoaded".$ownLoadVar[1].");tinyMCE.init({$initOptions});}}, 100);";
---------
What the problem?
The problem is that you would more text field, but the "plugin" only generates one variable(docLoaded) in the code. I did, that every variable unique be changing.

Sorry for my english.. next time i do better. :)
